definitions:
  dto.ErrorResponse:
    properties:
      message:
        example: invalid url
        type: string
    type: object
  dto.ShortenRequest:
    properties:
      url:
        type: string
    type: object
  dto.ShortenResponse:
    properties:
      shortCode:
        type: string
    type: object
info:
  contact: {}
paths:
  /{code}:
    get:
      description: Redirects using short code
      parameters:
      - description: Short code
        in: path
        name: code
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "302":
          description: Found
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Redirect to original URL
      tags:
      - URLs
  /shorten:
    post:
      consumes:
      - application/json
      description: Create a short URL from a long URL
      parameters:
      - description: URL payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ShortenRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ShortenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create short URL
      tags:
      - URLs
swagger: "2.0"
